### ISSUE TITLE
8.18.3 and 8.18.5:  Is TSMax the correct parameter?

### ISSUE THREAD

**Issue by andyburras** [cta-wave/device-playback-task-force#105]
My proposed text is using the TSMax parameter as the maximum permitted startup delay of the second presentation. Is this correct? Or is a specific configuration parameter required for this delay?

**Comment by yanj-github** [comment]
Resolved at meeting (21/12/2022) this issue can be closed. Please close it.

**Comment by gitwjr** [comment]
@andyburras See comment above. Please close if you agree with the resolution.

**Comment by gitwjr** [comment]
@andyburras 
Resolved. Closed.
