### ISSUE TITLE
§9.2 - Regular Playback - Audio duration

### ISSUE THREAD

**Issue by rcottingham** [cta-wave/device-playback-task-force#109]
Please can someone help to clarify the pre-conditions for "§9.2 Regular Playback of a CMAF Presentation" test: do audio and video tracks have the same duration?

If so, can the spec be updated to reflect this?

If the audio track is longer then how should it be handled? Does the audio truncate to match the video length? Does it finish separately to video? How does Test Runner handle this?

Thanks in advance for clarifying.

**Comment by jpiesing** [comment]
There was a long debate in various places about the definition of the duration of a CMAF presentation. Look at these ...

https://github.com/MPEGGroup/CMAF/issues/3
https://github.com/MPEGGroup/CMAF/issues/1

The conclusion was that the duration of the presentation (as an entity in its own right) was the duration of the video track. Hence I would expect any audio data before the start of the video track or after the end to be discarded.

@louaybassbouss @haudiobe

**Comment by gitwjr** [comment]
11-21-23: Video and audio should start at the same time. Close.
