### ISSUE TITLE
CEA-608/708 playback

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#11]
CEA-608/708 playback is considered in CTA WAVE content. The exact playback requirements need to be defined.

**Comment by haudiobe** [comment]
DPCTF 19/02/13: should be addresses in updated version of spec.
Needs:
- Playback requirements => What is stimulus? What is expected observation?
- Test Cases => As a second issue, please provide input
(Owner: Paul Hearty)

**Comment by haudiobe** [comment]
Not handled natively, but there is a javascript browsing. At this stage it is recommended to add a statement with a link to the library.

https://github.com/Dash-Industry-Forum/dash.js/blob/development/externals/cea608-parser.js

**Comment by gitwjr** [comment]
@haudiobe Per discussion on 2023/02/28, the following text was added at the end of clause 13.1: 
"North American regulations require support for CEA-608/708 subtitles under certain conditions. The WAVE Device Playback Capabilities Specification and the WAVE Device Test Suite do not include any requirements or tests for handling CEA-608/708 subtitles. However, the Dash-Industry-Forum has a .js script for handling 608. It can be found at https://github.com/Dash-Industry-Forum/dash.js/blob/development/externals/cea608-parser.js." 

Please review and edit if necessary. Then close this Issue.

**Comment by gitwjr** [comment]
Addressed in spec.
