### ISSUE TITLE
§9.3 - Random Access - A/V sync

### ISSUE THREAD

**Issue by rcottingham** [cta-wave/device-playback-task-force#110]
The stimulus (§9.3.4) for the "Random Access of a WAVE Presentation" test just mentions Video, but it is not clear how audio should be handled in order to be synchronised?

This links to the questions raised in issue #109.

Please can someone help to clarify?

**Comment by yanj-github** [comment]
The spec has change since we have last looked at this issue, me and @rcottingham will double check the spec wording from the latest release.

**Comment by yanj-github** [comment]
The latest spec change states that:
random_access_fragment: The CMAF Fragment number of the **video** track to start with. 
**Audio duration should match video duration.**
This is done now and can be closed.

**Comment by jpiesing** [comment]
> The latest spec change states that: random_access_fragment: The CMAF Fragment number of the **video** track to start with. **Audio duration should match video duration.** This is done now and can be closed.

Closed.
