### ISSUE TITLE
Review of DPCTF spec section 11.3.4 - HEVC options

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#112]
Reviewing 11.3.4, there are seem to be 5 content options that have more than one possible value or state.

1. Two options for default flags
A: default_sample_flags, sample_flags and first_sample_flags neither set in the TrackFragmentHeaderBox nor TrackRunBox 
B: default_sample_flags, sample_flags and first_sample_flags set in the TrackFragmentHeaderBox and TrackRunBox 
2. with (W) and without (W/O) picture timing SEI message
3. with (W) and without (W/O) with and without VUI timing information
4. Sample entry, see CMAF clause 9.4.1.2. Two options
'hvc1' sample entry type (parameter sets within the CMAF Header) 
'hev1' sample entry type (parameter sets within the movie fragment header)
5. Fragments containing one or multiple moof/mdat pairs – two options
A: Fragment is 1 chunk
B: Fragment contains multiple chunks (p-frame to p-frame with b-frames)

There are also a number of options that can only have one value or where it's only proposed to test one value.

1. 7.5.17	Track Run Box ('trun') - v1 – combined with SAP type 1 
2. 7.5.13	Edit List Box ('elst') - Absent
3. Initialization Constraints - Regular Switching Set, do not apply CMAF clause 7.3.4.2 and 9.2.11.4
4. CMAF Fragment durations - 2 seconds
5. B.2.4 - No SEI messages present.
6. B.3.3.2 - Single VPS.
7. B.3.3.3.2 - colour_description_flag set to 1.
8. B.3.3.3.2 - vui_time_scale and vui_num_units_in_tick set to constant.
9. B.5 - Settings according the requirements of the profile 'chh1' in Table B.1 of ISO/IEC 23000-19.

For switching sets, there is this ...
> Switching Set encoding following CMAF, Annex C recommendation. The following options exist:  
>  ◦ No subsampling.
>  ◦ Spatial subsampling of video according to CMAF, Annex C.2 recommendation.
>  ◦ Spatial and temporal subsampling and scaling of video according to CMAF, Annex C.1 recommendation for each 50 Hz and 60 Hz family.
> ◦ Regular encoding or CMAF, Annex C.9.4 recommendation for low-latency live.

There is also an exception ...
* At least one source sequence with another picture aspect ratio, non-square pixel with conformance cropping following the example in Annex C.8 of [CMAF] specification.

This list of options should be reviewed;
- Is there anything missing that's relevant in the real world?
- For the options where only one value is included, i) is including only one value reasonable and ii) if so, is the value included a reasonable one for the real world?
- For @nicholas-fr is this consistent with DVB TS 101 154?

_Originally posted by @jpiesing in https://github.com/cta-wave/Test-Content/issues/38#issuecomment-1504779252_

**Comment by jpiesing** [comment]
In https://github.com/cta-wave/Test-Content/issues/38#issuecomment-1505644365, it was noted that the initial HEVC test content does not comply with the above. Specifically;

> B.3.3.3.2 - vui_time_scale and vui_num_units_in_tick set to constant.
> NOK: vui_parameters_present_flag shall be set to 1
> NOK: is set to "hev1.2.4.L123.B0" or "hvc1.2.4.L123.B0" => current sample exposes hev1.2.4.L123.90

We should consider if the requirement in the current text is too restrictive.

**Comment by haudiobe** [comment]
Implemented here in [v2.08](https://standards.cta.tech/wg/dpctf/document/33886?downloadRevision=36697)
