### ISSUE TITLE
Review of DPCTF specification section 11.3.5 - HEVC test streams

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#113]
Based on the content options in DPCTF spec section 11.3.4 (see https://github.com/cta-wave/device-playback-task-force/issues/112), here's approximately what I'd expect to see in 11.3.5 if the same methodology as AVC would be followed.
- 1: A default stream based on one choice for each of the 5 content options that have more than one possible value or state
- 2: A non-default stream where each of the 5 content options that has more than one possible value or state has the alternate value to stream 1.
- 3, 4, 5, 6 and 7 - 5 debug streams that each differ from stream 1 by a different one of the 5 content options to enable debugging if stream 2 doesn't play correctly.
- streams used inside a switching set at a variety of resolutions and perhaps also some lower frame rates. If stream 1 is 1920x1080p50 then I guess the minimum here would be re-use of stream 1 plus 1920x1080p25 and 1280x720p25. For AVC, we went a lot lower in the resolutions but I have no idea if that's useful for HEVC.
- encrypted version of stream 1
- splicing streams, main and ad, both unencrypted and encrypted (i.e. total of 4)
- "At least one source sequence with another picture aspect ratio, non-square pixel with conformance cropping following the example in Annex C.8 of [CMAF] specification."

**Comment by jpiesing** [comment]
@nicholas-fr @rbouqueau

**Comment by rbouqueau** [comment]
Thanks Jon. LGTM.

3 remarks/questions below:

- For the frame rates, do we do it per frame rate family then? Or only one family?

> perhaps also some lower frame rates

In AVC we had higher frame rates as well. We have the sources and scripts for that so it's a matter of what needs to be tested.

> "At least one source sequence with another picture aspect ratio, non-square pixel with conformance cropping following the example in Annex C.8 of [CMAF] specification."

Is this specific to HEVC? May it relate to the confusion here? https://github.com/cta-wave/device-playback-task-force/issues/88

**Comment by haudiobe** [comment]
Implemented here in [v2.08](https://standards.cta.tech/wg/dpctf/document/33886?downloadRevision=36697)
