### ISSUE TITLE
Determine/prioritize what will/will not be included in the Final Launch Test Suite

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#115]
This issue is to track the action "Determine/prioritize what will/will not be included in the Final Launch Test Suite".

An early attempt at this is in the spreadsheet at https://docs.google.com/spreadsheets/d/1a4VfUydkB09a3kUWYuXT1qWq5RSKVt-rQ9LNWIR5pWM/edit?usp=sharing

**Comment by jpiesing** [comment]
From the April 26th meeting.

Unlikely to be included
* AVC
   * 9.6 Long Duration Playback
  
At risk
* AVC
    * 8.6    Regular Playback of Chunked Content
    * 8.7    Regular Playback of Chunked Content, non-aligned append
    * 8.15    Source Buffer Re-Initialization (without changeType)
    *  8.16    Source Buffer Re-Initialization (with changeType)
* AAC audio

**Comment by jpiesing** [comment]
Subsequently it seems there's another 4 that are at risk.
* random-access-of-a-wave-presentation and regular-playback-of-a-cmaf-presentation
See https://github.com/cta-wave/Test-Content-Generation/issues/62 and https://github.com/cta-wave/dpctf-tests/issues/110.
* switching-set-playback and fullscreen-playback-of-switching-sets
https://github.com/cta-wave/dpctf-tests/issues/108

**Comment by gitwjr** [comment]
At the 5/2/2023 Spring Forum WAVE Workshop priorities were assigned to the outstanding sections/test items for launch. Items #1-3 below were deemed to be crucial for launch. #4 is highly desirable. Confirmation that the resources are available for items 2-4 is pending discussions with Fraunhofer, Eurofins and @rbouqueau. 
1) Complete launch by the end of May, 2023 to meet deadlines for HbbTV next release. 
2) Complete work on Chunked Content (8.6, 8.7)
3) Complete work on Buffer re-initialization (without/with changeType) (8.15, 8.16)
4) Complete work on switching-set-playback and fullscreen-playback-of-switching-sets (without audio) (DPCTF Tests, issue 108)
5) AAC Audio: Automated testing will not be ready for launch. This includes random-access-of-a-wave-presentation and regular-playback-of-a-cmaf-presentation (with Audio)
6) AVC section 9.6 Long Duration will not be included in the Launch

**Comment by gitwjr** [comment]
**HEVC** WILL NOT be included in the Launch except for (**with changeType**), which WILL be included. Video AVC tests ARE in the launch except for long duration, which has not been validated and WILL NOT be included. (**Without changeType**) is not tested and WILL NOT be included. Audio is NOT in since automated observations have not been fully reviewed for release in this time frame. They are in the branch in GitHub.

**Comment by gitwjr** [comment]
Close. See DPCTF Tests issue #129 which will verify the warnings are implemented. The launch will include everything that is completed as of the time of launch. A warning will be added to tests that have not be validated on multiple devices as in a plugfest, etc. See DPCTF Tests issue #129 which will be closed when we can verify the warnings are implemented.
