### ISSUE TITLE
video decoder initialisation and playback duration

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#117]
There appear to be a number of alternative approaches for video decoder initialisation which have different consequences for playback duration and impact how this is measured. 
- Initialize the decoder after the call to the play method, decode and display the first frame the same as all the others when playback is fully ready to start, only show the first frame for the correct duration of that frame.
- Speculatively (software?) decode the first frame as soon as data is available without waiting for the play method to be called and display the first frame at the earliest possible moment. Keep showing the first frame until playback is fully ready to start and the second frame can be shown.
- An intermediate strategy between the first two where the first frame is (software?) decoded after the play method has been called but before proper video decoder initialization. Keep showing the first frame until playback is fully ready to start and the second frame can be shown.

Today the OF supports the first two of these but not the third - as discussed in https://github.com/cta-wave/device-observation-framework/issues/52 and in https://github.com/cta-wave/device-observation-framework/wiki/Observation-Algorithms#the-playback-duration-of-the-playback-matches-expected-duration .  ("Measurement starts from a detected frame after the play(). "). 

I think we need a wider discussion than just @yanj-github and myself about how to measure the duration of playback with the 3 different implementation approaches.

It's not explicitly or directly measurable but IMHO the playback duration should be defined as the time between when the media timeline starts advancing and when it stops advancing.
In our test sequences, we have a green marker frame at the start and a red marker frame at the end which sandwich the test content such as Croatia.
My proposal is that we should measure the time from when the second detected frame is first detected to when the last detected frame is first detected. We then need to correct for the difference between this and the CMAF duration which will be up to 2 frame durations.

As an example, consider the example screen captures included in https://github.com/cta-wave/device-observation-framework/issues/52. 
The second detected frame is most likely first detected in frame 71882 - although it might be detected in frame 71881.
The last frame would most likely be first detected in frame 75476 although it might be detected in frame 75475.
75476 minus 71882 (or 75475 minus 71881) is 3594 frames which, for a 120 Hz recording, is 29.95 seconds.
The CMAF track has duration 30s so if 2x25Hz frame durations are subtracted, is 29.92.
The difference between these is less than one frame at 25Hz although its outside our current pass / fail threshold.

We should also be looking at the tolerance we require which is currently +/- 20ms. If the QR code is detected one frame earlier or later in the recording then this uses just just over 8ms from this. That doesn't leave much tolerance for the implementation. 20ms is half a 25Hz frame or about 2.5 frames at 120Hz.

**Comment by jpiesing** [comment]
The OF has been fixed. The tolerance is a separate issue. I think we can close this.

**Comment by gitwjr** [comment]
Per @jpiesing this issue can be closed. The OF has been fixed. Tolerance has been discussed and has been/will be adjusted as necessary.
