### ISSUE TITLE
editorial nits

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#120]
Some editorial nits that don't need discussion.

1. 12.3.5.
> 12.3.4 Content Options
> The content options as defined in clause 10.3.2 apply. Specifically, a CMAF Switching Set with two CMAF Tracks of different bitrate ought to be added.
> 12.3.5 Test Content
> The content options as defined in clause 10.3.3 for 'caaa' apply.

"content options" in 12.3.5 is a copy/paste bug and should be "test content".

2. broken references to 10.2.3 (content options), 10.2.4 (test content) and 10.2.5 (playback requirements)

There are references to 10.2.3 that should be either 10.2.4 or 10.2.5 in 11.2.5, 10.7.2 and 10.6.2.
There are references to 10.2.4 that should be 10.2.5 in 11.2.6 and 10.2.3 in 10.6.5 and 10.7.5.
There is a reference to 10.2.5 in 11.2.7 that should be to 10.2.6.

**Comment by haudiobe** [comment]
Update uploaded to portal

1) addressed
2) 
- 11.2.5 updated, 10.6.2 and 10.7.2 should be correct
- 11.2.6 updated
- 11.2.7 updated

Rest should be ok
