### ISSUE TITLE
relax tolerance for currentTime observation

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#123]
Looking at the results from the London plugfest, probably the most commonly failed observation is the accuracy of currentTime.
Clause 8.2.5.2 of the DPCTF spec defines the accuracy as follows;

> The presented sample shall match the one reported by the currentTime value within the tolerance of +/- (2/framerate + 20ms).

The same text is in 8.18.5.2. and 8.23.5.2.

(2/12.5 + 0.02) = 180ms
(2/25 + 0.02) = 100ms
(2/50 + 0.02) = 60ms

Looking at most of the failures, a value between 100ms and 160ms would result in a lot more passes. Failures above 160ms are unusual.

We could either increase 2/framerate to 3/framerate or even 4/framerate. but that would make the test useless for the 12.5/15Hz video.

I would be inclined to increase the 20ms to perhaps 100ms. That would result in the following.

(2/12.5 + 0.1) = 260ms
(2/25 + 0.1) = 180ms
(2/50 + 0.1) = 140ms

We might consider changing "2/" to "1/" to reduce the variation between these. That would give 180, 140 and 120.

It should be noted that "2" and "20' are set in a configuration file so this would not be a change of code by Resillion.

@yanj-github

**Comment by jpiesing** [comment]
April 10th meeting 
Discussion
- Proposal to change 2/framerate + 20 to 1/framerate + 150.
- Issue is expected to be limitations on the communication between the media subsystem in the devices under test and the browser. Perhaps some mixture of overheads and/or infrequent polling or message passing.
- Makes analytic 2/framerate structuring less helpful. It was suggested to look at the test results & choose a value between 100 and 160.
- In theory can choose 0/framerate + 180.
- Concerns about more failures at higher framerates. Is this due to more errors at those framerates or because the threshold was lower (e.g. 100 falling to 60).

Proposal
- Reach tentative agreement here on 2 numbers - 0,180 if accepted by OF otherwise 1,150 
- Fraunhofer to use those numbers when running the OF, initially on the 3 consistent best TV sets from the plugfest
- Numbers to be confirmed (or not) when Resillion are available
- Then edit the DPCTF specification

Proposal approved.

**Comment by yanj-github** [comment]
Happy with approved proposal. This is just relax in tolerance, OF will compare given tolerance with detected difference no objection from our end.

**Comment by jpiesing** [comment]
> Happy with approved proposal. This is just relax in tolerance, OF will compare given tolerance with detected difference no objection from our end.

@yanj-github Do you believe the OF will accept 0/framerate +180 or do we need to use 1/framerate + 150?

**Comment by yanj-github** [comment]
> > Happy with approved proposal. This is just relax in tolerance, OF will compare given tolerance with detected difference no objection from our end.
> 
> @yanj-github Do you believe the OF will accept 0/framerate +180 or do we need to use 1/framerate + 150?

x/framerate used to find first and last possible camera frame numbers which we expect may match the status event QR currentTime.
I would prefer 1/framerate. 1/framerate means we seek one more frame for matching current time. For example if status ct detected on same recording frame we search for 1 more frame before it and 1 after it to find the matching time. We can consider 0.5 if you think 1 is too big. But I think we should give it a value instead of pure 0. 
How about choose between:
- 1/framerate + 150
- 0.5/framerate + 170?

**Comment by jpiesing** [comment]
> > > Happy with approved proposal. This is just relax in tolerance, OF will compare given tolerance with detected difference no objection from our end.
> > 
> > 
> > @yanj-github Do you believe the OF will accept 0/framerate +180 or do we need to use 1/framerate + 150?
> 
> x/framerate used to find first and last possible camera frame numbers which we expect may match the status event QR currentTime. I would prefer 1/framerate. 1/framerate means we seek one more frame for matching current time. For example if status ct detected on same recording frame we search for 1 more frame before it and 1 after it to find the matching time. We can consider 0.5 if you think 1 is too big. But I think we should give it a value instead of pure 0. How about choose between:
> 
>     * 1/framerate + 150
> 
>     * 0.5/framerate + 170?

1/framerate + 150 is good enough.

**Comment by jpiesing** [comment]
Implemented in Draft-CTA-5003-Ae-v2.04.

**Comment by nigelmegitt** [comment]
Sorry to dive in here without all the context, but it might be useful to note somewhere that it's not great practice to use currentTime for subtitle or caption presentation timing: with this relax in tolerance, I'd say it's actually unacceptable.

Apologies if this is off-topic, but for that use case, instead, TextTrackCue event (onenter and onexit) timing should be used, and the tolerance for accuracy there should be around ± 1/(framerate * 2), possibly with range limits e.g. minimum of 10ms, maximum of 80ms. Rationale:

* Quantisation errors can hugely increase required reading rate if not capped like this
* There are long-standing practical guidelines/requirements about not having subtitles slightly overlap shot changes temporally, because that causes a "double change" flicker, e.g. in the [BBC Subtitle Guidelines](https://www.bbc.co.uk/accessibility/forproducts/guides/subtitles/#Avoid-straddling-shot-changes).

**Comment by jpiesing** [comment]
> Sorry to dive in here without all the context, but it might be useful to note somewhere that it's not great practice to use currentTime for subtitle or caption presentation timing: with this relax in tolerance, I'd say it's actually unacceptable.

Thank you for diving in.

The tolerances in the WAVE tests and the observation framework are configurable. Typically we pick a value and run them on some current TV sets bought in the shops. When the tolerance is so demanding that few or no TV sets pass the tests then we normally relax the tolerance so that some TV sets pass. Tests that no TV sets pass will be ignored in the real world unless someone comes along with a far bigger stick than CTA and requires they be passed.

> 
> Apologies if this is off-topic, but for that use case, instead, TextTrackCue event (onenter and onexit) timing should be used, and the tolerance for accuracy there should be around ± 1/(framerate * 2), possibly with range limits e.g. minimum of 10ms, maximum of 80ms. 

CTA WAVE has previously discussed testing the use of TextTrackCue for this but never before had anyone make a statement this emphatic about its importance. EDIT: I have created [this issue](https://github.com/cta-wave/dpctf-tests/issues/221) to discuss how an automated test for the timing accuracy of TextTrackCue might work.

I note that there are a number of sources of timing error between video and subtitle rendering. Some of these may be in the browser but others may be in the TVOS and the underlying hardware. TextTrackCue may be better than currentTime as far as timing errors in the browser are concerned but I expect that both will converge on a single primitive at the porting interface between the browser and the TVOS. 

The [original ETSI git issue](https://labs.etsi.org/rep/HF/en301549/-/issues/124) that started this discussion says at the top that "+/-100ms requirement is very challenging and may not be met by current devices." and "Note: the 100ms requirement is not technically possible." From what I've seen of the results of the currentTime tests, I find it hard to believe an improvement from using TextTrackCue would be enough to meet the original +/- 100ms requirement.

> Rationale:
> 
>     * Quantisation errors can hugely increase required reading rate if not capped like this
> 
>     * There are long-standing practical guidelines/requirements about not having subtitles slightly overlap shot changes temporally, because that causes a "double change" flicker, e.g. in the [BBC Subtitle Guidelines](https://www.bbc.co.uk/accessibility/forproducts/guides/subtitles/#Avoid-straddling-shot-changes).

Is there any data that those requirements are met in the real world?

**Comment by nigelmegitt** [comment]
> The [original ETSI git issue](https://labs.etsi.org/rep/HF/en301549/-/issues/124) that started this discussion says at the top that "+/-100ms requirement is very challenging and may not be met by current devices." and "Note: the 100ms requirement is not technically possible." From what I've seen of the results of the currentTime tests, I find it hard to believe an improvement from using TextTrackCue would be enough to meet the original +/- 100ms requirement.

Oh, I'm told that browsers routinely fire TextTrackCue events within <10ms of the specified time. I think the mechanism they use is completely different from the one used to update currentTime and much more tightly tied to the media playback timeline. Clearly the the event handler needs to do work, and that will take a non-zero duration that also needs to be factored in. In the case of subtitles, replacing an HTML DOM fragment and rendering the result is something that browser engines are optimised for, performance wise.

My conclusion is that the rationale "the 100ms requirement is not technically possible" is false, though it is of course also dependent on a range of factors, including processor speed and load, so I can understand the concern about generalising it as a requirement. Perhaps there's a middle ground that everyone can accept, in terms of wording.

>Is there any data that those requirements are met in the real world?

I'm not sure what you'd class as data: this has been something that Teletext and CEA608 receivers would have done routinely for decades. Although the complexity of more modern subtitle solutions is indeed greater, the performance of processors is also orders of magnitude greater, and we should be expecting to achieve levels at least as good.

**Comment by jpiesing** [comment]
> > The [original ETSI git issue](https://labs.etsi.org/rep/HF/en301549/-/issues/124) that started this discussion says at the top that "+/-100ms requirement is very challenging and may not be met by current devices." and "Note: the 100ms requirement is not technically possible." From what I've seen of the results of the currentTime tests, I find it hard to believe an improvement from using TextTrackCue would be enough to meet the original +/- 100ms requirement.
> 
> Oh, I'm told that browsers routinely fire TextTrackCue events within <10ms of the specified time. 

I have great difficulty believing that in the general case. I could perhaps believe it in the case of a browser on a desktop PC with a software decoder that has been integrated with the browser by the browser developer themselves. 

> I think the mechanism they use is completely different from the one used to update currentTime and much more tightly tied to the media playback timeline. Clearly the the event handler needs to do work, and that will take a non-zero duration that also needs to be factored in. In the case of subtitles, replacing an HTML DOM fragment and rendering the result is something that browser engines are optimised for, performance wise.
> 

This is all plausible when looking just at the browser itself. My impression from other discussions is that the errors are introduced by the underlying operating system and hardware decoders and communication between those components and the browser.

It's also worth noting that modern TV sets include picture processing components after the video decoder that have variable delays depending on whether the user has selected (for example) vivid mode or some other mode. Some of these may apply only to video (i.e. potentially be applied before video and graphics are combined) and some to both video and graphics. In some modes, a delay of more than one frame could be introduced. 

> My conclusion is that the rationale "the 100ms requirement is not technically possible" is false, though it is of course also dependent on a range of factors, including processor speed and load, so I can understand the concern about generalising it as a requirement. Perhaps there's a middle ground that everyone can accept, in terms of wording.
> 

IMHO it's more dependent on hardware and software architecture.
Current hardware architectures probably do not have optimised support enabling sync of graphics to video.

> > Is there any data that those requirements are met in the real world?
> 
> I'm not sure what you'd class as data: this has been something that Teletext and CEA608 receivers would have done routinely for decades. Although the complexity of more modern subtitle solutions is indeed greater, the performance of processors is also orders of magnitude greater, and we should be expecting to achieve levels at least as good.

I expect those were either completely hardware implementations or at least had a substantial degree of hardware assistance. General purpose operating systems don't necessarily do real-time very well.
