### ISSUE TITLE
Random access from one place in a stream to a different place in the same stream: unclear duration calculation

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#124]
As discussed in https://github.com/cta-wave/device-observation-framework/issues/75, the duration observation needs to exclude the last frame before the seek, the elapsed time of the seek and potentially the first frame after the seek. 
- The last frame before the seek may be frozen on-screen for the duration of the seek.
- The first frame after the seek may be rendered differently in the same way as the start frame of the entire stream

It is proposed to clarify 8.23.5 of the DPCTF spec as follows (additions shown in italics as github doesn't do underlines well).

> 1) The playback duration shall match the duration of the CMAF Track, i.e. TR[k,S] = TR[k,1] + td[k] taking into account: 
> - Missing starting and ending frames. 
> - Potential start frames being rendered before playback. 
> - _Potential first frame after the seek being rendered before playback_
> - Frozen last frame after the playback ended. 
> - _Frozen last frame before the seek_
> - Skipped frames between random_access_from and random_access_to. 

@yanj-github

​​

**Comment by yanj-github** [comment]
Thanks @jpiesing proposed change looks good to me.

**Comment by jpiesing** [comment]
Also 8.23.5 needs the reference to 8.2.5.2 changed to 8.4.5.2 to include the increase of the maximum permitted startup delay.
Implemented in Draft-CTA-5003-Ae-v2.04.
