### ISSUE TITLE
Audio-Video Synchronization observation

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/device-playback-task-force#129]
What are we checking for Audio-Video Synchronization observation?

The spec wording:
_9.2.5.4	Audio-Video Synchronization
The mediaTime of the presented audio sample shall match the one reported by the video currentTime value within the tolerance of +40 ms / -120 ms._

Is this meant to comparing audio media time with reported application layer current time? I don't think it is correctly checking Audio-Video Synchronization. We are allowing a bigger tolerance for video sample with current time match. "_8.2.5.2 The presented sample shall match the one reported by the currentTime value within the tolerance of +/- (1/framerate + 150ms)._" 

I think we should compare actual presentation time of matching audio and video sample pair.

**Comment by jpiesing** [comment]
I agree this is a bug. We should be comparing the time of the displayed video (as burnt into the QR code) with the time from the PN audio.

**Comment by haudiobe** [comment]
DPCTF:
- thanks. We will fix the bug in the next version @haudiobe

**Comment by haudiobe** [comment]
fixed in version 2.09 as follows

The `mediaTime `of the presented audio sample shall match the `mediaTime `of the presented audio sample within the tolerance of +40 ms / -120 ms.

**Comment by yanj-github** [comment]
I suggest the following:
_The presented audio sample that has the same mediaTime as the video sample shall be presented jointly within the tolerance of +40 ms / -120 ms._

**Comment by haudiobe** [comment]
DPCTF 2024/07/03

Updated according to last comment. integrated into v2.0.10
