### ISSUE TITLE
Implementation using existing “canPlay(type)” queries is inefficient and inaccurate

### ISSUE THREAD

**Issue by cta-source** [cta-wave/device-playback-task-force#2]
_Captured from 2016-08-03 DPCTF slide deck:_
Implementation using existing “canPlay(type)” queries is inefficient and inaccurate
- We need some better registry and compatibility
- If a platform says “yes” to canPlay(type), then there must be certain aspects being fulfilled.
- The registry file requires some discovery method, e.g. reserved file name, and parsing.  It can work with proprietary players as well as Web apps on a browser.  I assume a Type 1 native player would work with either. 
- Some parameters would need to be set by users through some UI. That includes many that should be discoverable by the hardware through EDID, etc.; but that doesn’t actually work today.

**Comment by mwatson2** [comment]
Is this effectively a dup of #5 ?
