### ISSUE TITLE
Playback requirements for CMAF HEVC HHD10 ('chh1')

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#22]
- Where is the media profile defined?
- What are Capability Discovery Options?
   - <Define how the media profile capability signaling is donediscovery of the media profile may be done, including existing practices>
- What are the Source Buffer Initialization Requirements?
   - Codec
   - max frame rate
   - etc.
- What are the Playback Requirements?
  - via reference to the above playback requirements define what the media profile playback requirement is

**Comment by haudiobe** [comment]
10.2.3	Media Profile: CMAF HEVC HHD10 ('chh1')
The details for this profile will be added to an updated version of the specification after a questionnaire to the media profile proponents.

**Comment by haudiobe** [comment]
I added the HEVC Test Content Options to an updated dpctf specification here

https://standards.cta.tech/apps/org/workgroup/dpctf/download.php/34886/dpctf-s00001-v032-WAVE-DPC-v1.12.docx

In order for better tracking, I also provided the content options for each of the profiles here:
-	https://github.com/cta-wave/Test-Content-Generation/blob/master/Instructions/chh1.md

**Comment by jpiesing** [comment]
I've tried to make the same style of sparse matrix for HEVC as for AVC following the list of content options. The results are somewhat different from the proposal at the end of the document from @haudiobe .

https://docs.google.com/spreadsheets/d/1wjj4U35uUboOM7sO06AqC3rsFtL_mffgSyPVJGYb7V0/edit?usp=sharing

The biggest difference from AVC is that the limited number of resolutions tested. For AVC, we did a good set of resolutions covering many (most) of those that might get used in a ladder. The original proposal here was just 4 combinations, 1280p50/60, 1280p25/30, 720p50/60 and 720p25/30. For avc, we had 15. I've only put 4 in this google doc.

**Comment by haudiobe** [comment]
DPCTF Call:
- Agree to update based on the proposal from @jpiesing

**Comment by nicholas-fr** [comment]
I have 2 changes to propose, unless there is a particular reason these tests are relevant for AVC but not for HEVC. This relates to the discussion about consistency in test content across different codecs.

1. We should include 1 test stream with Picture timing SEI present (pic_struct=0). 
While this is optional and all content is progressive, the presence of this SEI should be tested as it is for AVC.


2. In order to test the presence of constant vui_time_scale and vui_num_units_in_tick, at least 1 test stream including VUI timing information should be created.

**Comment by haudiobe** [comment]
DPCTF Call on 2022/03/09:
- agree on both, needs implementation

**Comment by gitwjr** [comment]
Deferred to HEVC implementation

**Comment by haudiobe** [comment]
Implemented here in [v2.08](https://standards.cta.tech/wg/dpctf/document/33886?downloadRevision=36697)
