### ISSUE TITLE
MSE buffering and Timing

### ISSUE THREAD

**Issue by wilaw** [cta-wave/device-playback-task-force#29]
This is a former User Agent Integration Spec issue which has been assigned to DPCTF.

Issues relates to 

1. the ability of the device sourcebuffer to hold a certain quantity of data in its buffer
2. The rate at which that data can be appended
3. The minimum append size

**Comment by jpiesing** [comment]
To be more specific, here are some issues where some content providers have found it necessary to be more precise for MSE implementations in media devices;

1) That it must be possible to append a defined amount of data to the video SourceBuffer before data starts being evicted.
2) That playback must begin once a defined amount of data has been appended
3) That once enough data has been appended for playback to begin (previous point) then playback must begin within a defined time
4)  That end of stream cannot be signalled until the amount of remaining data that has not been presented is less than a defined amount (more an HTML5 media element issue than a MSE one)
5) That once end of stream has been signalled, all media data must still be presented (more an HTML5 media element issue than an MSE one)

**Comment by jpiesing** [comment]
The original of this issue is here - https://github.com/w3c/webmediaporting/issues/10

**Comment by haudiobe** [comment]
19/02/13 (DPCTF): Relevant topics - all quality related so relevant for DPCTF. 
Options:
- covered by existing requirements
-  integrate into existing requirements by bug fix
- create new playback requirements
We invite for analysis and more discussion. Expect updates to next version of spec.

**Comment by haudiobe** [comment]
2020/07/08 f2f: W3C Issue
