### ISSUE TITLE
Type 1 Playback Requirements

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#31]
The specification addresses today primarily Type 3 playback. "In this specification, the primary focus is on type 3 based playback – i.e. it is assumed that the application does manifest download and processing and can establish and playback WAVE content using a set of track buffers. The application of the requirements in this specification to type 1 playback may be addressed in a future version of the specification." Type 1 would need someone to come up with a specific model.

Are there examples for type 1 playback available? DVB-DASH? HLS? Can we reference?

**Comment by haudiobe** [comment]
19/02/13 (DPCTF): Open until NAB f2f. If no comments are received, we will close type 1 playback and not define playback requirements. Spec will be updated accordingly.

**Comment by haudiobe** [comment]
I have not thought about the details. However, what I believe what could be done that the tests are not forced by a javascript, but by a properly constructed manifest.
This would surely result in some work, but I believe this could be well done, once we have the type-3 tests established. I would suggest to work in sequence, do type-3 first.

**Comment by haudiobe** [comment]
2020/07/08 : we will not address this issue in the next version

**Comment by gitwjr** [comment]
Close. Reopen if necessary.
