### ISSUE TITLE
Playback Requirements for CMAF AAC Core ('caac')

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#35]
11.2.2	Media Profile: CMAF AAC Core ('caac') 
Initiated here: https://1drv.ms/w/s!AiNJEPgowJnWgbpZesbLvglzCXVlSg

Proponents were asked to provide input

**Comment by haudiobe** [comment]
DPCTF 2022/02/09:

- Specification Text added to https://standards.cta.tech/apps/org/workgroup/dpctf/download.php/35020/dpctf-s00001-v032-WAVE-DPC-v1.14.docx in clause 12.2
- Please check implementation by 2022/02/23 DPCTF call.

**Comment by gitwjr** [comment]
@haudiobe
Reopen if not done.
