### ISSUE TITLE
Playback Requirements for AC-4, Single Stream (‘ca4s’)

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#39]
Add playback requirements for this profile

**Comment by haudiobe** [comment]
DPCTF 2022/02/09:

- Specification Text added to https://standards.cta.tech/apps/org/workgroup/dpctf/download.php/35020/dpctf-s00001-v032-WAVE-DPC-v1.14.docx in clause 12.6.
- Please check implementation by 2022/02/23 DPCTF call.

**Comment by gitwjr** [comment]
@haudiobe Reopen if necessary.
