### ISSUE TITLE
Playback Requirements for DTS-HD Audio ('dts1')

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#41]
Add playback requirements for this profile

**Comment by haudiobe** [comment]
DPCTF 2022/02/09:

- Initial Specification Text added to https://standards.cta.tech/apps/org/workgroup/dpctf/download.php/35020/dpctf-s00001-v032-WAVE-DPC-v1.14.docx in clause 12.8.
- Expect updates from proponents, then we will also issue last call for comments

**Comment by gitwjr** [comment]
Reviewed 11/22/2022 and left open.

**Comment by gitwjr** [comment]
The spec has been updated. Tests are not included in Launch.

**Comment by haudiobe** [comment]
Added to v2.0.10
