### ISSUE TITLE
Configuration Discovery and usage capability for encryption

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#47]
How can we discover the configuration of the supported encryption/decryption? Add this to clause 7.

**Comment by haudiobe** [comment]
2020/07/08: EME capability query is well-defined. Defined and supported. Some documentation is available that may be reused.

@wilaw provides this information: https://research.akamaized.net/capabilitiescheck.html
https://isemesupportedyet.netlify.app/

Check with developers how they do this

**Comment by haudiobe** [comment]
this is work in progress

**Comment by gitwjr** [comment]
@haudiobe 
Please provide more information on what this issue addresses.

**Comment by gitwjr** [comment]
This issue was addressed per @haudiobe.
