### ISSUE TITLE
New Playback Requirement: Playback Other than Real Time

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#49]
8.16	Playback Other than Real Time
8.16.1	Background
This test refers to the playback of content faster or slower than real-time, or even in reverse direction. Content conforms even in different speed to the profile/level constraints of decoder.
There are three ways to do this:
•	Play at X times as long as it is in the decoder profile/level constraint (app forwards all content to the device and device plays with X times).
•	Use special content (e.g., I-frame only content, to address any of these issues – and use the above).
•	Download key frames from regular content and feed those into the MSE source buffer. 

The first version of this specification does not define a test for this.

**Comment by haudiobe** [comment]
Overlaps with Low Latency #71 - merge

https://www.w3.org/TR/html51/semantics-embedded-content.html#playing-the-media-resource

De-prioritize this one, merge into #71

**Comment by dsilhavy** [comment]
Note: reverse playback/negative playback rates are not supported natively by the HTML5 video element: 
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate

_If playbackRate is negative, the media is **not** played backwards._

Related request for dash.js: https://github.com/Dash-Industry-Forum/dash.js/issues/3570

**Comment by jpiesing** [comment]
> If playbackRate is negative, the media is **not** played backwards.

Interesting. That restriction is not in the HTML spec and indeed could be argued to conflict with the HTML spec which explicitly addresses negative playback.

![image](https://user-images.githubusercontent.com/8490792/113150199-1b5d8300-9234-11eb-9bd1-c3cdf6e6c3b7.png)

![image](https://user-images.githubusercontent.com/8490792/113150306-38925180-9234-11eb-9ad0-d487e39b7854.png)

![image](https://user-images.githubusercontent.com/8490792/113150499-71322b00-9234-11eb-91f6-d1127e949a4b.png)

**Comment by dsilhavy** [comment]
Interesting. I did a quick check for negative playback rates

- Chrome throws: VM16730:1 Uncaught DOMException: Failed to set the 'playbackRate' property on 'HTMLMediaElement': The provided playback rate (-0.1) is not in the supported playback range.
- Firefox throws: Uncaught DOMException: Operation is not supported
- Safari: No error, but seems to adjust everything <0 to 0. So playback pauses.

**Comment by andyburras** [comment]
`I did a quick check for negative playback rates`

Interesting. One to check with HATF, but as the WMAS snapshot and WPT testing is based on the common functionality supported by the current mainstream browser code bases then I guess this falls outside WAVE scope?

**Comment by haudiobe** [comment]
Not part of new tests - may be removed

**Comment by gitwjr** [comment]
Deferred for future work.

**Comment by haudiobe** [comment]
this seems to be implemented now

**Comment by jpiesing** [comment]
> this seems to be implemented now

Yes, this is essentially a superset of #71 and the proposed implementation of that is sufficiently generalised the playback rates are read in from a config file and the code and media is the same.

**Comment by haudiobe** [comment]
Implemented with #71
