### ISSUE TITLE
New Playback Requirement: Truncated Playback and Restart

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#51]
8.18	Truncated Playback and Restart
8.18.1	Background
Playback can be stopped at an arbitrary presentation time within a CMAF fragment and playback can be started with a new presentation seamlessly.
The first version of this specification does not define a test for this.

**Comment by dsilhavy** [comment]
Not completely sure what this test requires in terms of MSE. A seek to the beginning of the presentation? Or completely truncate the SourceBuffer and start buffering again including a seek to the beginning of the new presentation?

**Comment by jpiesing** [comment]
> Not completely sure what this test requires in terms of MSE. A seek to the beginning of the presentation? Or completely truncate the SourceBuffer and start buffering again including a seek to the beginning of the new presentation?

I don't really understand this one. @haudiobe ?

**Comment by haudiobe** [comment]
part of the new tests
