### ISSUE TITLE
New Playback Requirement: Event Message Processing

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#53]
8.20	Event Message Processing
CTA WAVE content may contain event messages of relevance for the application.
The first version of this specification does not define a test for this.

**Comment by haudiobe** [comment]
(19/11/06 DPCTF)
- W3C work does some work on this
- DASH-IF (see published information) + MPEG developed (see CDAM.1) an Event Processing Model as well (more or less completed)
- dash.js has a polyfill that will do the work (preferably make this polyfill library independent of dash.js)
We start from the DASH-IF/MPEG model for playback requirements (Thomas)

For making the tests complete, we need
- Content Requirements for Event messages in CTA WAVE Content Specification - at this stage no difference CMAF, only guidelines and recommendations. Would be good to have a specific normative section in Content Specification (augmented with recommendations and guidelines) => 2020 spec.
- Need Test cases and test material for this purpose
(John)

**Comment by haudiobe** [comment]
An initial proposal is provided here, but needs more work: 
https://1drv.ms/w/s!AiNJEPgowJnWgos-u32ftrH96QvscQ?e=vPuxHh

**Comment by jpiesing** [comment]
#76 makes the point that some of the streams should have events in them as a matter of principle.

**Comment by dsilhavy** [comment]
dash.js uses the IsoBoxer library to check for EMSG boxes: https://github.com/madebyhiro/codem-isoboxer

Workflow is as simple as we check for EMSG after segments have been downloaded. Event handling is done in a separate class (EventController). We support version 1 and 2 events. This logic could be reused if required, although decoupling of other dash.js parts is required.

**Comment by jpiesing** [comment]
As far as I can tell. MSE implementations and browsers don't do anything with emsg boxes & should ignore them. If this is correct then there's nothing for WAVE to test here.

**Comment by dsilhavy** [comment]
I think Iraj and DASH-IF are working on this in the context of MSE v2. I agree that currently nothing can be tested here with MSE v1

**Comment by haudiobe** [comment]
At this stage this is implemented as a javascript library. No test are needed. It would be reasonable to refer to 
1) processing model
2) Javascript library that can be used as a reference that includes
  a) IsoBoxer library to check for EMSG boxes: https://github.com/madebyhiro/codem-isoboxer
  b) https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streaming/controllers/EventController.js

Propose to add the above informative description.

**Comment by gitwjr** [comment]
@jpiesing noted that we decided to test to confirm event messaging does not break anything. 
Part of RFP: Change to test content generation scripts. Need to add event message to some content and do simple tests to see if anything breaks.  
11/22/2022: No resolution.

**Comment by gitwjr** [comment]
Included in latest contract. Close.
