### ISSUE TITLE
New Playback Requirement: Joint Playback of Video and Subtitles

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#54]
9.5	Joint Playback of Video and Subtitles
9.5.1	Background
This test specifies the joint playback of video and subtitles and the proper rendering.
No tests are defined for this feature in the first version of the specification.

**Comment by haudiobe** [comment]
(19/11/06 DPCTF) 
* defer until we have test content and clearer requirements

**Comment by jpiesing** [comment]
If subtitles are decoded by the DASH / HLS player, are there any requirements in the WAVE spec?

**Comment by haudiobe** [comment]
would be good to have, but CTA WAVE will not take the lead on this.

**Comment by jpiesing** [comment]
If the player is rendering the subtitles / captions then it won't be able to do this any more accurately than the implementation of MediaElement.currentTime. See #28

**Comment by haudiobe** [comment]
needs discussion - see also TWG.

**Comment by gitwjr** [comment]
Addressed in the DPCTF spec section on Subtitles.
