### ISSUE TITLE
Multitrack and Multilanguage Audio 

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#58]
Multi-track and Multi Language refers to the case that for example multiple audio streams are offered, each with a different language, providing dubbed versions. However, the content specification  is silent about this. Until there is no understanding on what such content may look like, playback requirements are hard to generate.

**Comment by jpiesing** [comment]
I'm confused why there would be any specific playback requirements for multi-track or multi language audio in the general case. It's just a different CMAF switching set (DASH Adaptation Set). It's different for the object based audio technologies if there's a bitstream with multiple preselections but there are other issues to be addressed there. MPEG participants and other people with access to the MPEG document archive should look at document M54461.

**Comment by haudiobe** [comment]
no problem identified for now. Can re-open when we have more detailed content requirements.
