### ISSUE TITLE
Playback Requirements and Content for Captions

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#59]
Add more details

**Comment by jpiesing** [comment]
In type 3 playback, the captions are rendered by the JavaScript DASH player and not by the browser so perhaps this can be closed?

**Comment by haudiobe** [comment]
Unless there is test content and clear requirements, nothing will be done.

**Comment by haudiobe** [comment]
TWG discussion on how much we do on subtitles. Needs more discussion

**Comment by gitwjr** [comment]
Out of Scope. Close.
