### ISSUE TITLE
Fragment selection ambiguous in Random Access To Time test

### ISSUE THREAD

**Issue by angusbell** [cta-wave/device-playback-task-force#61]
In Section 8.4.4, the selection of the first fragment to push to the Source Buffer is ambiguous, when random_access_time falls on a fragment boundary. When this happens, there will be two values of r for which
tk[k,r]≤ random_access_time and tk[k,r+1]≥ random_access_time
holds true.

This could potentially cause different receiver behaviour where the first fragment pushed may or may not be presented. Then, the observation that the total playback duration is a specific value would not be tenable.

**Comment by angusbell** [comment]
I think one of "<=" or ">=" needs to be a strict "<" or ">", but we need to decide which.

**Comment by haudiobe** [comment]
Accepted. v1.0.8 already provides some updates, but additional work needed.

**Comment by haudiobe** [comment]
Implemented in v1.38
