### ISSUE TITLE
required observations for random access not complete

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#62]
In the published spec, the required observations for random access aren't complete.

8.3.5.1 says
> Every sample S[k,s]shall be rendered and the samples shall be rendered in increasing presentation time order.•The playback duration of the playback matches

8.4.5.1 says
> Every sample S[k,s]with presentation time larger or equal to random_access_timeshall be rendered and the samples shall be rendered in increasing presentation time order.

Neither of them say that no samples earlier than the specified time/segment shall be rendered. Both of them should be changed to say this.

**Comment by haudiobe** [comment]
(DPCTF 2020/04/22): We agree on the problem. Implementation needed.

**Comment by gitwjr** [comment]
1/31/2023: The change was made to the spec. Closed.
