### ISSUE TITLE
Every video frame ... shall be rendered such that it fills the entire video output window

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#63]
(Edited now I've seen WAVE 10.2.1)
Many places in the Device Playback spec have language like this;

>8.11.5.2 Video
>If   the track is a video track, then:
>•Every video frameS[k,s]shall be rendered such that it fills the entire video output window.

There doesn't appear to be a definition of "video output window".

Section 10.2.1 of the WAVE device spec requires a selection of 16:9 resolutions be supported which is fine when the video output window is also 16:9 but what if the video output window isn't 16:9?

Scaling that doesn't preserve aspect ratio may not be tested at all except to a limited extent, e.g. if required by global content providers or if required by resident apps in a particular device. 
Alternatively attempting to fill a rectangle whose aspect ratio is not 16:9 may be implemented by keeping the video as 16:9 and leaving the remainder as black. The latter is what HbbTV requires.

I propose (request?) that the device playback spec be changed to either 1) permit video scaling that preserves aspect ratio and fills the remainder with black or 2) make behaviour out of scope when the video output window doesn't have the same aspect ratio as the video.

**Comment by jpiesing** [comment]
I just found this in 5.2.2.4.

> With setting up a source buffer for a video media type, either:
> • a pre-determined display window that matches the aspect ratio and size of the
> content (height and width) is established, or
> • a full-screen display is established.
> With setting up a source buffer for an audio media type, an audio output is established.

If the display window here is the same as the "video output window" in the observations then this issue becomes purely editorial - I would suggest changing 5.2.2.4 to use "video output window" and perhaps add a cross-reference to 5.2.2.4 from the first place where "video output window" is used.

**Comment by haudiobe** [comment]
(DPCTF 2020/04/22): Agreed to proposed change.

**Comment by gitwjr** [comment]
Jan 31, 2023: 
@haudiobe @jpiesing 
I reviewed the document. There is no longer a 5.2.2.4. The text in question is in 5.2.2 of DPCTF spec v1.36 (latest as of today). It states "•	A pre-determined **display video output** that matches...". The observations use the term "•	shall be rendered such that it fills the entire **video output window** following..." (8.2.5.2 - 8.11; 8.15.5.2; 8.16.5.2). 
I suggest changing the terminology in 5.2.2 to match the observations per the comment. If no comments, close.

**Comment by gitwjr** [comment]
Feb 8, 2023: Implemented. Close.
