### ISSUE TITLE
media samples of different tracks with the same presentation times are presented jointly.

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#64]
9.2.5.1 says;
> While continuing playback, the media samples of different tracks with the same presentation times are presented jointly

What does "jointly" mean? This is a complete rats nest. 

This ITU-R recommendation gives guidance on AV sync accuracy
https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.1359-1-199811-I!!PDF-E.pdf.

Summary:
- AV sync difference of +45ms to -125ms is not perceptible (+ means audio ahead of video, - means audio behind video)
- Difference up to +90ms to -185ms is acceptable

Some global VOD service providers have their own requirements.

Content providers have constraints on their production and distribution infrastructures but still want the result to be within the ITU guideline which may result in very demanding requirements being asked from player/device implementers and their suppliers. For VOD it may be possible to fine-tune the AV sync during the encoding / packaging process but less so for live.

Implementers and their suppliers also have constraints. The sum of the worst case content provider constraints (for live) and the worst case implementer constraints is typically outside the ITU recommendation.

It also gets more complex when the display and the speakers are in a different device from the video and audio decoders. A TV set or mobile phone using the integrated speakers / headphone socket for audio output is best case. As soon as the display or the speakers move to the other side of an interface such as regular HDMI or HDMI (e)ARC or bluetooth or SPDIF then the device doing the A/V decoding and sync may have to estimate the delays on the other side of the interface. Some devices may permit users to configure this delay but it's still error prone. It's very unclear what is a realistic interpretation of "presented jointly" under these circumstances.

**Comment by haudiobe** [comment]
(DPCTF 2020/04/22):  Functional problems and performance problems. May need to be parameterizable.

Agreed to f2f discussion.

**Comment by jpiesing** [comment]
Here is a proposal ...

The definition of jointly is that audio 
- shall be presented no more than 45ms ahead of the corresponding video and should be presented no more than 35ms ahead of the corresponding video
- shall be presented no more than 125ms after the corresponding video and should be presented no more than 50ms after the corresponding video.

This is based on the ITU document and some other requirements we've seen.

**Comment by gitwjr** [comment]
1/31/2023: No comments received. Closed.
