### ISSUE TITLE
use of the playout parameter unclear

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#67]
A parameter "playout" is used to define which CMAF track to use as the source for the each fragment to append to the Source Buffer. For example, in 8.10.3
> playout[i]: Provides the CMAF track number for every fragment position i=1,...,N. This value shall be between 1and K.    

I can't find a definition of what playout[i] is initialised to.

Am I missing something?

**Comment by jpiesing** [comment]
If playout [i] can be initialised to random number within the specified range then what's written at the moment is fine (although it would be good to be explicit that it could be initialised to random numbers). If some intelligence is needed, e.g. stepping through from 1 to K incrementing by +1 and then by -1 then this certainly needs to be written down.

**Comment by haudiobe** [comment]
Accepted, v1.0.8 already includes some improvements and links to the tests. Further improvement will be done.

**Comment by gitwjr** [comment]
Jan 31, 2023: Implemented. Close.
