### ISSUE TITLE
duplication in 8.10.5.2 Video?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#68]
8.10.5.2 Video, says the following;

> In addition, for video the following is expected to be observed:
> •The rendering for each track is scaled to the height and width of the predetermined window.
> •No visible shifts of objects in the video.
> •No visible spatial offset of pixels in the video.
> Based on this, if the track is a video track, then: 
> •Every video frameS[k,s]shall be rendered such that it fills the entire video output window.

Isn't there a substantial overlap between the first and last bullet points?

**Comment by haudiobe** [comment]
Accepted - description will be improved to combine.

**Comment by gitwjr** [comment]
Implemented in v1.38 of spec.
