### ISSUE TITLE
possible duplication in 8.5.5.2 and 8.10.5.2

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#69]
8.5.5.2 and 8.10.5.2 says this;

> No visible shifts of objects in the video.
> • No visible spatial offset of pixels in the video.
> Based on this, if the track is a video track, then:
> • Every video frame S[k,s] shall be rendered such that it fills the entire video output window.

Does shift mean spatial shift (or some other shift)?
If shift mean spatial shift, how does this differ from spatial offset?
How could a spatial shift or offset not result in the video frames no longer filling the video output window?

The way I would test this would be to check the position of the QR codes in the video but I'm not sure I understand the observations well enough.

**Comment by jpiesing** [comment]
The original author of this text needs to comment. The mezzanine content has a QR code at a fixed location.

**Comment by haudiobe** [comment]
Agree, combine in one sentence including pixels and make objects an example.

**Comment by gitwjr** [comment]
Implemented in v1.38 of spec.
