### ISSUE TITLE
possible duplication in 8.12.6?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#70]
8.12.6 contains the following;

> 8.12.6 Expected Observation
> The playback is continuous and time-accurate.
> No unnecessary startup delay, e.g., initializing a secure video path, negotiating a secure HDCP display connection, etc. 
> Every sample shall be rendered and shall be rendered in order.
> The playlist plays until the end.
> The duration of playback matches the duration of the CMAF Presentation, i.e. Last frame is presented at T2 + duration of the CMAF Track.
> The rendering time report on the API matches the rendered sample.

Is "The playlist plays until the end." covered by the observation immediately before it? If every sample is rendered doesn't this mean the playlist plays to the end?

Isn't "The playback is continuous and time-accurate." partly a duplicate of "Every sample shall be rendered and shall be rendered in order."?

**Comment by jpiesing** [comment]
The author of this text needs to comment.

**Comment by haudiobe** [comment]
agree - needs implementation.

**Comment by gitwjr** [comment]
Jan 31, 2023: Implemented. Closed.

**Comment by gitwjr** [comment]
Feb 2, 2023: Reopened. Needs final review.

**Comment by gitwjr** [comment]
Implemented in v1.38 of spec.
