### ISSUE TITLE
testing seek from one place in a stream to another

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#72]
In live situations, if playback at non-integer speeds >1.0 doesn't work then the alternative is to seek forwards in the stream.

The tests we have for seek are 8.3 Random Access to Fragment, 8.4 Random Access to Time and  9.3 Random Access of a WAVE Presentation. All of these test starting to play a stream from somewhere other than the beginning. There is no test of seeking where the stream is already playing before the seek is performed. Among other things, this will have different timing considerations and ideally video/audio decoders would not need to be re-initialised.

At the minimum, I recommend adding a version of 9.3 where the CMAF Presentation is played from the beginning for say 20s and then a seek is done to the desired location. 

Ideally the test would be more complex and the target of the seek would be a time that does not correspond to the start of a CMAF Fragment.

**Comment by jpiesing** [comment]
I tried copying and editing 9.2/9.3 to merge them into a play followed by a seek but the style they're written in stumped me :(

**Comment by haudiobe** [comment]
Agree on test. Needs implementation.

**Comment by jpiesing** [comment]
It would be good to have a few variations on this.
- Seek into a different CMAF segment
- Seek within the same CMAF segment (not chunked content)
- Seek within the same CMAF segment (chunked content, different chunk)

**Comment by dsilhavy** [comment]
Agree on this comment "Ideally the test would be more complex and the target of the seek would be a time that does not correspond to the start of a CMAF Fragment"

For a long time, dash.js adjusted the initial seek target for livestreams to align with fragment/segment boundaries. We will change this behavior in 4.0 and allow initial seeking to arbitrary positions in a segment. This will result in an initial playback position closer to the desired live edge.

**Comment by gitwjr** [comment]
@dsilhavy 
Has this test been added? If so, close.

**Comment by gitwjr** [comment]
Implemented in v1.38 of spec. @jpiesing will add improved text.

**Comment by gitwjr** [comment]
Test and observation are in place. Per discussion on DPCTF call held March 8, 2023, this issue can be closed.
