### ISSUE TITLE
improve clarity about which requirements are really derived from MSE and which are not

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#73]
Many of the requirements in the device playback capabilities spec are really just derived from MSE and "just" go deeper into detail. In many cases, the requirement is how an expert would expect a reasonable implementation of MSE to work. 

It would be helpful if any requirements that go beyond MSE could be explicitly identified. These could be;
- functional requirements
- non-functional requirements such as performance

**Comment by jpiesing** [comment]
Each of the tests in sections 8 and 9 follows a standard format.
nn.1 Background
nn.2 Pre-conditions 
nn.3 Parameters and Variants
nn.4 Stimulus
nn.5 Required Observation

We may consider adding a new heading "Specification References" or "Key Specification References" or "Significant Specification References". This could then contain quotes and links to MSE and/or CMAF and/or our own specs.

**Comment by haudiobe** [comment]
Agree on this one, but we need to check how we can still keep this "somehow" on a generic level. Jon and Thomas work on more details, what applies from MSE and what is new. @jpiesing will start.

**Comment by gitwjr** [comment]
Implemented. Close.
