### ISSUE TITLE
definition of fullscreen for 8.11

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#75]
> 8.11 Full Screen Playback of Switching Sets
> 8.11.1 Background
> Fullscreen playback ensures that the device provide proper scaling and letter boxing.
> 8.11.2 Pre-conditions
> Same as documented in clause 8.9.2.
> Output is set to fullscreen.

> 8.11.5.2 Video
> If the track is a video track, then:
> • Every video frame S[k,s] shall be rendered such that it fills the entire video output window.

The video is specified to be 16:9. What if the aspect ratio of the display is not 16:9 (e.g. many? mobile devices), what is expected?
- Crop, preserving video picture aspect ratio
- Fit video to display preserving video picture aspect ratio and filling remainder with (say) black
- Scale video to display **not** preserving video picture aspect ratio

What if the display has overscan like some TVs still do?

TVs still sometimes (in some modes) support over-scan

**Comment by jpiesing** [comment]
You can see a lengthy discussion here about phone screen aspect ratios being 18:9 or even larger.

https://www.quora.com/What-are-the-advantages-and-disadvantages-of-18-9-ratio-screen-for-phones

It needs to be clear what the test would do on an 18:9 display phone and what would be a pass.

**Comment by haudiobe** [comment]
Would expect that if you 16:9 video, then it means no cropping of the video. You get black at the corners. You also keep square pixel. preserve aspect ratio, full video available, no cropping. 

Document this observation. Should we also have none 16:9 content to test this experience? 

4:3, 18:9, 21:9? Issue of new content, defer this.

**Comment by jpiesing** [comment]
Consider this
"the video shall be scaled such that one side of the video fills the video/broadcast object fully without cropping the picture. The aspect ratio shall be preserved. Along the side where the video is shorter than the container, the video shall be centred. The area of the video plane not containing video shall be opaque black.".

"container" might not be the right word.

**Comment by gitwjr** [comment]
Implemented in v1.38 of spec. @jpiesing will add improved text.

**Comment by jpiesing** [comment]
Here is the revised proposal

> "the video shall be scaled such that one side of the video fills the video output window fully without cropping the picture. The aspect ratio shall be preserved. Along the side where the video is shorter than the video output window, the video shall be centred. The area of the video plane not containing video shall be opaque black.".

i.e. the term "video output window" has been inserted which is widely used elsewhere in the spec.

**Comment by gitwjr** [comment]
@jpiesing If I read this correctly, the following text will replace item 2 in its entirety in 8.11.5.2 (i.e. deleting "i.e. If the output window aspect ratio is matching..." and "If the...is not matching...".

"Every video frame s[k,s] shall be rendered such that the video shall be scaled such that one side of the video fills the video output window fully without cropping the picture. The aspect ratio shall be preserved. Along the side where the video is shorter than the video output window, the video shall be centered. The area of the video plane not containing video shall be opaque black." 

If this is the case I will make the edit to the spec along with the several others noted elsewhere.

**Comment by gitwjr** [comment]
Implemented in DPCTF v1.42.
