### ISSUE TITLE
Low Latency: Accelerated/Decelerated Playback

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#79]
Background: For low-latency, to catchup with the desired latency or to avoid buffer underrun, the application may want to accelerate/decelerate playback of the media

Stimulus: Playback regular content and fill buffer. Then decelerate and accelerate content playback by a certain factor.

Expected Observation: Video is played at adjusted framerate. Audio is played properly - sounds good, for example applying pitch corrected. details are tbd

CMAF content: regular cmaf content, but may be media profile specific and should also be test for audio and video combined.

**Comment by haudiobe** [comment]
May be two tests, one with and one without pitch correction.

**Comment by jpiesing** [comment]
I agree with adding this but there are a lot of small variations and we need to think carefully what is important to avoid a combinatorial explosion.
* How important is it to test video without audio and audio without video?
* If we only test CMAF Presentations (video+audio) how does that work for the different codecs? Would it be reasonable to test each video media profile with (say) HE-AAC and each audio media profile with AVC?
* Is there really a use-case for decelerated playback?

**Comment by jpiesing** [comment]
Duplicate of #71

**Comment by haudiobe** [comment]
accepted as duplicate.
