### ISSUE TITLE
The issue of “seamless switching” needs further discussion.

### ISSUE THREAD

**Issue by cta-source** [cta-wave/device-playback-task-force#8]
_Captured from 2016-08-17 DPCTF meeting discussion_
From the discussion at the time of the meeting: It was suggested that not all the codec etc. standards are complete when it comes to seamless switching.  Clearly seamless switching is a desirable capability, but we need to be careful about whether all the technologies are fully spec'd in this regard.

**Comment by haudiobe** [comment]
This issue is included in the draft spec and needs to be progressed
