### ISSUE TITLE
Low-Latency: Playback over Gaps

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#81]
Background: For low-latency, it may happen more often that content is not received, but to maintain latency, playback needs to continue

CMAF Content: Regular low-latency content

Testing: Add content, add a gap, add content. Continue playback.

Observation: maintain timing against real-time

**Comment by haudiobe** [comment]
Another issue is AV Sync is maintained. And another fail is just stop.

Check existing tests, if this already covered.

**Comment by jpiesing** [comment]
Does MSE require this? I've re-read the MSE spec and cannot see anything. If it's valid behaviour for an MSE implementation to stop at a gap then the DASH player would have to handle the recovery. This sounds like something that should be raised as a feature for the next version of MSE.

**Comment by dsilhavy** [comment]
This is important in my opinion. MSE implementations are usually not able to handle gaps and will stop playback. For instance:

1. Append a segment with range [0-2]
2. Append next segment with range [2.1 - 4]
3. Small gap between [2-2.1]
4. The corresponding SourceBuffer will have two buffer ranges: [0-2] and [2.1 - 4] --> SourceBuffer.buffered.length = 2
5. Playback will stall after 2 seconds

Players like dash.js and Shaka implement a gap handling logic. Common approach:
* For VoD: Do an immediate seek once a gap is reached
* For Live: Wait for the duration of the gap before seeking to maintain a consistent live edge

From my experience browser might be able to handle very small gaps but usually they just stall and wait for the gap to be filled. An active seek by the player is required to overcome such situations.

**Comment by jpiesing** [comment]
> From my experience browser might be able to handle very small gaps but usually they just stall and wait for the gap to be filled. An active seek by the player is required to overcome such situations.

This doesn't surprise me at all. In which case, what is to be tested here? Is this essentially a test that seeking past a gap works?
e.g. the test code would wait for a stalled event & (based on the example above) seek forwards to 2.1 and then play?

**Comment by dsilhavy** [comment]
> > From my experience browser might be able to handle very small gaps but usually they just stall and wait for the gap to be filled. An active seek by the player is required to overcome such situations.
> 
> This doesn't surprise me at all. In which case, what is to be tested here? Is this essentially a test that seeking past a gap works?
> e.g. the test code would wait for a stalled event & (based on the example above) seek forwards to 2.1 and then play?

Yes I think this would be a reasonable test. The difference between a "normal" seek is that we have at least two buffered ranges. Maybe this can also be part of the test. We create a gap on purpose and expect two ranges to be defined with:
range.end(1) - range.start(0) = duration of gap. In our example above this would be equal to 0.1.

**Comment by haudiobe** [comment]
Part of the new test cases
