### ISSUE TITLE
8.8 very unclear about how the playout[] has to be constructed

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#83]
8.8 is very unclear about how the playout array is supposed to be constructed in order to test what's supposed to be tested.

Suppose Switching Set #1 has tracks A, B and C and Switching Set #2 has tracks D, E, F.
Suppose each track lasts 1 minute.

Would playout[] contain the full minute from Switching Set #1 and then the full minute from Switching Set #2 ?

What characteristics would be needed for choosing tracks A, B, C and D, E, F?

**Comment by haudiobe** [comment]
Check Fraunhofer implementation and improve the description. We need to be more prescriptive here.

**Comment by gitwjr** [comment]
@jpiesing 
Per Thomas, the preference is to add the text to make it more clear but can leave it as it is. Please review and close if appropriate.

**Comment by jpiesing** [comment]
I will try to produce a one sentence summary of what the current tests do.

**Comment by jpiesing** [comment]
This issue is overtaken by the addition of clause 8.8.3 item 2 where playout [i] is defined so it could be closed.

Looking at test-config.json, the playout[] array is currently the following;

  "avc_12.5_25_50-online/playback-over-wave-baseline-splice-constraints__splice_main_splice_ad.html": {
     "playout": [
       [1, 1, 1],  [1, 1, 2],  [1, 1, 3],  
       [2, 1, 1],  [2, 1, 2],  [2, 1, 3],
       [1, 1, 4],  [1, 1, 5],  [1, 1, 6]
     ]
  },

Which is not the same as 8.8.3 item 2. I think this is correct and the text in 8.8.3 item 2 is wrong.

Also the link in 8.8.3 item 2 is wrong as additional lines have been added to test-config.json so line numbers 133 and 143 are wrong.

Also the test content for 8.8 is temporary and new content is needed which may result in playout[] needing to be modified. This is tracked by https://github.com/cta-wave/dpctf-tests/issues/101 and https://github.com/cta-wave/Test-Content/issues/19.

Proposal: Update the numbers in 8.8.3 item 2 to match the above and delete the link.

**Comment by gitwjr** [comment]
@haudiobe Please review @jpiesing proposed text change.

**Comment by gitwjr** [comment]
@haudiobe Reopen if you disagree with Jon's text changes.
