### ISSUE TITLE
8.8 observations based on a single track but test is about splicing 2 switching sets

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#84]
In 8.8, the observations are written based on a single track but test is about splicing 2 switching sets. 

Surely the playback duration needs to match the sum of the durations of the media played from Switching Set 1 and the media played from Switching Set 2?

**Comment by haudiobe** [comment]
Correct - update the observations!

**Comment by gitwjr** [comment]
Implemented. Close.
