### ISSUE TITLE
Testcase proposal:  MSE appendWindow

### ISSUE THREAD

**Issue by dsilhavy** [cta-wave/device-playback-task-force#85]
MSE based DASH players use `appendWindowStart` and `appendWindowEnd` to align period boundaries with buffer ranges:

 _Coded frames with presentation timestamp within this range are allowed to be appended to the SourceBuffer while coded frames outside this range are filtered out. The append window start and end times are controlled by the appendWindowStart and appendWindowEnd attributes respectively._

This has implication in scenarios in which a negative `eptDelta` or a `pdDelta` are present, i.e segments overlap the period boundaries.

For instance, if a video segment is partially shifted out of the appendWindowStart the IDR frame at the beginning of the segment is "cut" and the successive media frames(up to the next IDR) can not be decoded. This results in gaps in the SourceBuffer.

I propose to add a test case to check this behavior for different combinations and media types:
* Shift segment out of appendWindowStart for audio and video. Video will probably result in buffer gaps. What happens with audio? Audio samples should be still be decodable (no gap)
* Shift segment out of the appendWindowEnd for audio and video. Does this work if the video contains b frames? I expect yes because the DTS != PTS but would be interesting to verify. Same for audio.

**Comment by jpiesing** [comment]
I will add this to the survey.

**Comment by haudiobe** [comment]
part if the new DPC tests. Can be closed
