### ISSUE TITLE
Test proposal: Transition between encrypted and non encrypted segments

### ISSUE THREAD

**Issue by dsilhavy** [cta-wave/device-playback-task-force#86]
A transition from encrypted to non encrypted content (and vice versa) might be interesting to test. For instance this can be important in the context ad-insertion. From dash.js experience:

**Case 1**
1. Append init segment of encrypted content
2. Append media segment of encrypted content
3. Call changeType()
4. Append init segment of unencrypted content
5. Append media segment of unencrypted content
6. Playback works

**Case 2**
1. Append init segment of unencrypted content
2. Append media segment of unencrypted content
3. Call changeType()
4. Append init segment of encrypted content
5. Append media segment of encrypted content
6. MSE error

**Comment by dsilhavy** [comment]
After discussion with @louaybassbouss 

This test already exists in 8.14 Sequential Playback of Encrypted and Non-Encrypted Baseline Content. An interesting addition to 8.14 might be a codec change between the two types of content and a call to changeType(). The implementation of 8.14 already calls changeType() if a codec change occurs. Only thing required for this enhanced test might be additional content with different codecs.

Please feel free to close this issue if not relevant.

**Comment by jpiesing** [comment]
> This test already exists in 8.14 Sequential Playback of Encrypted and Non-Encrypted Baseline Content. An interesting addition to 8.14 might be a codec change between the two types of content and a call to changeType(). The implementation of 8.14 already calls changeType() if a codec change occurs. Only thing required for this enhanced test might be additional content with different codecs.

Thanks. How widely deployed is changeType()? Does it work well enough to be used on media devices?

**Comment by dsilhavy** [comment]
> Thanks. How widely deployed is changeType()? Does it work well enough to be used on media devices?

From my experience it is supported by Safari, Firefox and Chrome on Desktop devices. I expect it to work in Chromium Edge as well. According to https://developer.mozilla.org/en-US/docs/Web/API/SourceBuffer/changeType it also works on Chrome Android. iPad OS would be interesting as well, as the MDN site does not differentiate between iOS and iPadOS

**Comment by haudiobe** [comment]
8.14 attempts to cover this, but lacks detailed description. The above text should be used as baseline for improving 8.14. Thanks

**Comment by gitwjr** [comment]
@dsilhavy @haudiobe 
Review text in 8.14 and either close the issue if adequate or edit to resolve the issue.

**Comment by gitwjr** [comment]
Implemented in v1.38 of spec.
