### ISSUE TITLE
Test proposal: Track and ABR switch

### ISSUE THREAD

**Issue by dsilhavy** [cta-wave/device-playback-task-force#87]
When a track is switched (for instance switch of audio language) or the quality is increased (Rep switch up) it is required to replace/remove existing parts of the buffer.

Propose to add something like the following:

1. Append init segment of track A
2. Append multiple media segments of track A
3. Start playback
4. During playback remove everything that is in the buffer event at the current play position
5. Potential call to changeType()
5. Append init segment of track B
6. Append multiple media segments of track B
7. Playback should resume with new track

**Comment by dsilhavy** [comment]
Discussed with @louaybassbouss

- Related test: 8.10 Overlapping Fragments: Might be required to distinguish between different implementations here
  -  a) Overwrite/Replace existing segments in the buffer via append. No remove before overwrite. This is how the current test cases is implemented (compliant with the test specification)
  - b) Remove existing buffer ranges before appending new segments. In this context: Remove everything even at the current play position. Playback should stall until new segments are appended.

Suggest to add a variant b) to this testcase as well.

**Comment by jpiesing** [comment]
>     * b) Remove existing buffer ranges before appending new segments. In this context: Remove everything even at the current play position. Playback should stall until new segments are appended.
> 
> 
> Suggest to add a variant b) to this testcase as well.

Just for curiosity, how important is variant b)? When is it used by dash.js?

**Comment by dsilhavy** [comment]
We are using variant b) when an audio track switch is performed. I never carefully tested variant a) though. I just remember that long time ago we saw some problems with a) on Firefox. Really long time ago though :)

For video we also replace existing buffer parts when the quality is increased. However, we always keep the current segment in the buffer and never replace anything right at the current playposition.

**Comment by haudiobe** [comment]
DPC Spec covers this in 8.10. No actions needed. Propose to close
