### ISSUE TITLE
Test content not 16:9

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#88]
https://github.com/cta-wave/Test-Content-Generation/issues/32

Some help if needed here.

**Comment by haudiobe** [comment]
DPC Editing: Unclear what we can do - help wanted.

**Comment by haudiobe** [comment]
Closed - can also be closed here

**Comment by gitwjr** [comment]
Closed per @haudiobe comment after discussion on March 8 DPCTF call.
