### ISSUE TITLE
incorrect references in DPCTF spec section 8.11

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#91]
Section 8.11, Full Screen Playback of Switching Sets, has repeated references to 8.9.

![image](https://user-images.githubusercontent.com/8490792/124621707-c8bae500-de7a-11eb-8eb1-ed57f3481417.png)

8.9 is Out-Of-Order Loading & there is no obvious reason why 8.11 should reference this.
Perhaps it's 8.5, Switching Set Playback, that should be referenced?

This is based on discussion in https://github.com/cta-wave/dpctf-tests/issues/42#issuecomment-874824522

**Comment by haudiobe** [comment]
addressed in v1.0.8
