### ISSUE TITLE
Possibly incorrect cross-reference in DPC spec section 8.13 Restricted Splicing of Encrypted Content

### ISSUE THREAD

**Issue by cta-source** [cta-wave/device-playback-task-force#92]
Based on a recent draft, dpctf-s00001-v032-WAVE-DPC-v1.02:

Section 8.13, _Restricted Splicing of Encrypted Content_, states that it follows the methods and requirements from section 8.11, _Full Screen Playback of Switching Sets_.  This statement is in 8.13.2 as follows:

> 8.13.2	Stimulus and Observation
> Playback Observation: The same as 8.11. 
> 

Should that reference to 8.11 actually be 8.8, _Playback over WAVE Baseline Splice Constraints_? 

In addition, 8.14.2 has a similar reference to 8.11

**Comment by haudiobe** [comment]
Fixed in v1.0.8
