### ISSUE TITLE
add definition for start-up delay to the spec

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#93]
A definition needs to be added to the spec for start-up delay.
A proposal based on from https://github.com/cta-wave/device-observation-framework/issues/27 is as follows;

> The start-up delay is the time from when the play method is called to the next time when a video frame starts being displayed.
> NOTE 1: The first video frame may be displayed without waiting for play to be called in which case the start-up delay is time time from when play is called to when the second frame starts being displayed.
> NOTE 2: The first frames of video in the content may not be displayed at all. In which case the start-up delay is the time from when play is called to when the first frame that is displayed becomes visible.

I'm not sure where this definition would go.

**Comment by jpiesing** [comment]
@haudiobe @louaybassbouss @yanj-github

**Comment by poolec** [comment]
What is the reason for NOTE 2?  In my view, it's an error if any of the content is missing.

**Comment by louaybassbouss** [comment]
> What is the reason for NOTE 2? In my view, it's an error if any of the content is missing.

@poolec correct but another observation related to dropped frames will fail in this case.

**Comment by jpiesing** [comment]
> What is the reason for NOTE 2? In my view, it's an error if any of the content is missing.

We have a separate observation that every frame is displayed. This has configurable tolerances for dropped frames at the start, at the end & in between. This permits negotiation between an implementer and a service provider / platform. If such a negotiation would happen & a service provider / platform would agree to accept (say) one dropped frame at the start then the duration test should pass.

**Comment by haudiobe** [comment]
DPC Editing call proposes 120ms.  this is already implemented in v1.0.7
