### ISSUE TITLE
change "may" to "shall" in DPCTF spec 8.4 otherwise it's identical to 8.3

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/device-playback-task-force#95]
The "may" in section 8.4.1 of the DPCTF spec shown below means that the random access here could also occur at the start of a fragment (at least it's not excluded from being the start of a fragment).

![image](https://user-images.githubusercontent.com/8490792/146195531-568ce836-ddaf-4f57-b02d-fa97bf5283e3.png)

If the random access would occur at the start of a fragment then 8.4 becomes identical to 8.3.

Either "may" is changed to "shall" or 8.4 is deleted - I think the latter is wrong as random access to a time that is not the start of a fragment is something that is at risk of failure.

**Comment by haudiobe** [comment]
DPCTF 2022/01/26: 

Proposed to replace with 
A track is randomly accessed and playback, starting from a specific time onwards.
The time for playback generally does coincide with the start of a Fragment. For testing, a time other than the start of a CMAF Fragment shall be used. Testing when accessing at a start of a CMAF Fragment is covered in clause 8.3.

**Comment by haudiobe** [comment]
implemented in version v1.11

**Comment by gitwjr** [comment]
Implemented. Close.
