### ISSUE TITLE
Subtitle Testing clause 13.3

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/device-playback-task-force#96]
… Caption/Subtitle Testing …
 
The primary focus of CTA WAVE is content playback by an HTML5 app using MSE and, where needed, EME.  When using MSE/EME, subtitles and captions are typically decoded and presented by a JavaScript library that is included with the application. For example, for IMSC1, see https://github.com/sandflow/imscJS.
 
Such libraries have dependencies on the HTML5 user agent implementation, such as graphics rendering and synchronization to the video and audio. The latter is done by the JavaScript library reading the HTML5 currentTime property which is verified as part of WAVE testing. 
The tests in this specification include observations for the accuracy of the fit between the value of currentTime and the currently output video or audio; best results occur when this fit is frame accurate and a standard JavaScript subtitle or caption library is used.

[JRP2] I'm not sure about the previous phrase. Perhaps delete after the ";"? A standard subtitle/caption library may be no better or worse than one that's been customised. If someone would be pedantic, what is a "standard" one? Is imscJS standard? IMHO that's not a useful discussion to have.

[JRP2] What about adding the following;
Content playback using a native media decoder / renderer is not a priority for WAVE.
For native media rendering (the so-called "type 1"), a number of resources exist for testing a subtitle decoder; examples for IMSC1/TTML include: https://github.com/w3c/imsc-tests and https://dvb.org/specifications/verification-validation/dvb-ttml-subtitling-test-streams/.
[JRP2] We could also add the following;
WAVE is happy to receive donations of test content for testing decoding and presentation of IMSC1/TTML captions and subtitles but will not be funding developments of this material. 

[JRP2] Not for publication but an example of such a possible test content would be an incremental extension to the long duration mezzanine content mentioned for the next iteration of DPCTF tests. As well as 60-90-120 minutes of video and audio, there could be the same duration of subtitles/captions. TP Vision has an interest in making such test content in the context of DVB-I where we are using native DASH players. If we did this, donating it to WAVE as an incremental extension would make most sense.  

....
 
Do we need a statement of WAVE’s decision on how much we will do on captions/subtitles, links to content, links to more sites, …?
 
[JRP2] I think I've proposed that above. If not then please given an example of such a statement?

**Comment by haudiobe** [comment]
This issue also relates to #11

**Comment by cta-source** [comment]
_Here is an attempt at a gestalt of the email discussions mentioned above._

… Caption/Subtitle Testing …
 
The primary focus of CTA WAVE is content streaming and playback by an HTML5 app using MSE and, where needed, EME. During such playback, subtitles and captions are typically decoded and presented by a JavaScript library that is included with the application. For example, for IMSC1, see https://github.com/sandflow/imscJS or https://github.com/Dash-Industry-Forum/dash.js.
 
Such libraries have dependencies on the HTML5 user agent implementation, such as synchronization to the video and audio. Such synchronization is done by the JavaScript library reading the HTML5 currentTime property which is verified as part of WAVE testing. The tests in this specification include observations for the accuracy of the fit between the value of currentTime and the currently output video or audio. These tests are part of WAVE’s overall focus on HTML5/MSE/EME testing. Other basic subtitle/captioning functionality in HTML5/MSE/EME playback is not tested by WAVE.

WAVE does not currently provide test suite support for native media rendering (the so-called "type 1"). However, a number of resources exist for testing a subtitle decoder; examples for IMSC1/TTML include: https://github.com/w3c/imsc-tests (which is cited in the WAVE Media Profile for IMSC1 Text) and https://dvb.org/specifications/verification-validation/dvb-ttml-subtitling-test-streams/. The W3C publishes IMSC1 test vectors at https://github.com/w3c/imsc-tests (which is cited in the WAVE Media Profile for IMSC1 Image).

WAVE collects and develops test content to meet industry needs for streaming interoperability. If an organization has test content suitable for testing decoding and presentation of IMSC1/TTML and wishes to add to the WAVE pool of qualified material, please contact standards@CTA.tech.

**Comment by haudiobe** [comment]
DPCTF 2022/02/09

- Does dash.js reuse imscJS? Does dash.js include CEA-608/708? Once clarified, please update sentence. (check with Daniel)
- currentTime is observed in every test and it is checked if is correct. This means for every test, the rendering of subtitles is tested => already included in the above text

**Comment by jpiesing** [comment]
Here are a few small editorial changes that might be considered in addition to the one about dash.js re-using imscJS.

Such libraries have dependencies on the HTML5 user agent implementation, such as synchronization to the video and audio. Such synchronization is done by the JavaScript library reading the HTML5 currentTime property which is verified as part of WAVE testing. The tests in this specification include observations for the accuracy of the fit between the value of currentTime and the currently output video or audio. These tests are part of WAVE’s overall focus on HTML5/MSE/EME testing. Other basic subtitle/captioning functionality in HTML5/MSE/EME playback is not tested by WAVE.

to

Such libraries have dependencies on the HTML5 user agent implementation, such as _graphics rendering and_ synchronization to the video and audio. ~~Such~~ _This_ synchronization is done by the JavaScript library reading the HTML5 currentTime property which is verified as part of WAVE testing. The tests in this specification include observations for the accuracy of the fit between the value of currentTime and the currently output video or audio. These tests are part of WAVE’s overall focus on HTML5/MSE/EME testing. Other basic subtitle/captioning functionality in HTML5/MSE/EME playback is not tested by WAVE.

**Comment by cta-source** [comment]
The material is now incorporated in Section 13 (Media Profiles) of the DPCTF spec. My only comment now is that section 10.4 is a little out-of-sync. In fact, much of the text in 13 could also go in 10.4, or be moved to it.

**Comment by gitwjr** [comment]
The text from @cta-source has been incorporated into the spec. Section 10.4 now refers to Section 13. Close.
